dol_ldap:
    domains:
        # First domain
        server1:
            driver:
                host: localhost
                port: 389
                username: cn=admin,dc=proxym-it,dc=com
                password: admin
                bindRequiresDn:  true
                accountCanonicalForm: 3
            user:
                baseDn: ou=USER,dc=proxym-it,dc=com
                attributes:
                    - { ldap_attr: uid,  user_method: setUsername }
                    - { ldap_attr: mail,  user_method: setEmail }
                filter: (&(ObjectClass=Person))
