security:

    erase_credentials: false

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        chain_provider:
            chain:
                providers: [fos_userbundle, dol_ldapbundle]
        dol_ldapbundle:
            id: dol_ldap.security.user.provider
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            dol_ldap:   ~
            provider: chain_provider
            form_login:
                login_path: /login
                always_use_default_target_path: false

            logout:
                path: logout
                target: /login
            anonymous: true

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/welcome, role: ROLE_USER }
        - { path: ^/user, role: ROLE_ADMIN }

